version: '3'
services:
  database:
    image: mariadb:11
    container_name: database-container
    environment:
      MYSQL_ROOT_PASSWORD: db_password
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql

  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-container
    depends_on:
      - database
    ports:
      - "3000:3000"
